# Generated by Django 5.1.2 on 2024-10-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_profile_blood_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
