# Generated by Django 5.1.2 on 2024-10-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_testresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='Status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='total_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
