# Generated by Django 5.1.2 on 2024-10-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_testresult_status_testresult_total_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='emotions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
