# Generated by Django 5.1.2 on 2024-10-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_testresult_emotions'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
