# Generated by Django 5.1.2 on 2024-10-20 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_testresult_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testresult',
            options={'ordering': ['-date']},
        ),
    ]
