# Generated by Django 5.1.2 on 2024-10-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_testresult_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='emotion_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
